config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'welcome/home'
  root 'welcome#home'

  get 'signup', to: 'users#new'
  resources :users, except:[:new]
  resources :profiles, :lists, :movies, :tags 


  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'addtolist/:id', to: 'movies#addtolist'
  post 'removefromlist/:id', to: 'movies#removefromlist'
  post 'addlike/:id', to: 'movies#addlike'
  post 'removelike/:id', to: 'movies#removelike'
  get 'testbg', to: 'welcome#testbg'
  get 'admin', to: 'user#admin'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :movie
    belongs_to :profile

end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :profile
  has_many :list_movies
  has_many :movies, through: :list_movies

end

app/models/list_movie.rb
class ListMovie < ApplicationRecord
  belongs_to :movie
  belongs_to :list
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :list_movies
  has_many :lists, through: :list_movies
  belongs_to :tag
  has_many :likes

end

app/models/profile.rb
class Profile < ApplicationRecord
  has_one :list, dependent: :destroy
  belongs_to :user
  has_many :likes

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :movies
end

app/models/tmdb_api.rb
class TmdbApi
    include HTTParty
    BASE_URL = "https://api.themoviedb.org/3/search/movie?"
    MOVIE_URL = "https://api.themoviedb.org/3/movie/"
    API_PARTIAL_URL = "api_key=#{ENV['TMDB']}"

    def query
        request = HTTParty.get(BASE_URL+API_PARTIAL_URL+"&language=en-US&" + @search_format).to_json
        @request_hash = JSON.parse(request)
    end

    def movie_query(id)
        request = HTTParty.get(MOVIE_URL + id + "?" +API_PARTIAL_URL).to_json
        @request_hash = JSON.parse(request)
    end
    def initialize(user_search_input)
        @search_format = "query=#{user_search_input.gsub(" ", "+")}&"
    end

    def build_info
        #byebug
        info_hash = self.query['results'][0]
        if info_hash
            description = info_hash['overview']
            image = info_hash['poster_path']
            language = info_hash['original_language']
            release_date = info_hash['release_date']
            id = info_hash['id'].to_s
            second_hash = self.movie_query(id)
            if second_hash["backdrop_path"] != nil
                backdrop = second_hash["backdrop_path"]
            else
                backdrop = nil
            end
            return {:backdrop => backdrop, :description => description, :image => image, language => language, :release_date => release_date}
        else
            return {:description => "This movie was not found at the moment!", :image => "w94_and_h141_bestv2/ezQpwZnYcOEeyER0wKSdATkxUUE.jpg", language => "NA", :release_date => "The Past"}
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :profiles, dependent: :destroy

  validates :username, presence: true, uniqueness: {case_sensitive: false},
            length: {minimum: 3, maximum: 25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i     
  validates :email, presence: true, uniqueness: {case_sensitive: false},
            length: {maximum: 105},
            format: { with: VALID_EMAIL_REGEX}
  has_secure_password

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

### not sure if needed


end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    before_action :current_user, :current_profile

    def index
        @tags = Tag.all
    end
    def show
        @tag = Tag.find(params[:id])
        session[:return_to] = tag_path(@tag)
    end


    private

    def current_user
        if !session[:user_id]
            return redirect_to "/"
          end
        @current_user ||= session[:user_id] && User.find_by("id = ?",session[:user_id])
    end
    def current_profile
        @current_profile ||= session[:profile_id] && Profile.find_by("id = ?",session[:profile_id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user, :current_profile
  skip_before_action :current_profile, :only => [:show, :new, :create]
  skip_before_action :current_user, :only => [:new, :create]
  
  def index 
    @users = User.all 
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    if @user.profiles.length == 0
      return redirect_to new_profile_path
    end
    session[:profile_id] = Profile.find(@user.profiles[0].id).id
    @current_profile ||= session[:profile_id] && Profile.find_by("id = ?",session[:profile_id])
  end

 
  def edit 
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      if @user.id == 1
        @user.admin = true
        @user.save
      else
        @user.admin = false
        @user.save
      end
      flash[:notice] = "Welcome #{@user.username}! You have successfully logged in!"
      session[:user_id] = @user.id
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    @user = User.find(session[:user_id])
    if @user.update(user_params)
      flash[:notice] = "User successfully updated"
      redirect_to @user
    else
      flash[:error] = "E-mail must be in valid E-mail format"
      render 'edit'
    end
  end


  def destroy
    @user = User.find(session[:user_id])
    @user.destroy 
    session[:user_id] = nil
    session[:profile_id] = nil
    redirect_to "/"
  end
  
  private 
  
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def current_user
    if !session[:user_id]
      return redirect_to "/"
    end
    @current_user ||= session[:user_id] && User.find_by("id = ?",session[:user_id])
    
  end
  def current_profile
    #byebug
    @current_profile ||= session[:profile_id] && Profile.find_by("id = ?",session[:profile_id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-3 text-white">
    <div class="container text-center">
      <small>Copyright &copy; Will Duiker & Brandon Fonnemann </small>
    </div>
  </footer>

app/views/layouts/_messages.html.erb
  <% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show mb-0"  role="alert">
      <%= msg %>
      <button type ="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

app/views/layouts/_navbar_edit.html.erb
<nav class="navbar navbar-expand-md navbar-dark">
 <%= link_to image_tag("/images/notflix.png"), class: "navbar-brand ml-3 mt-2"%>

  <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item active">
        <%=link_to "Movies", movies_path, class: "nav-link text-white font-nf"%>
      </li>

      <li class="nav-item">
      <%=link_to "Genres", tags_path, class: "nav-link text-white font-nf"%>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white font-nf" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Welcome <%=@current_user.username.titleize %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to "Account Homepage", user_path(@current_user), class: "dropdown-item font-nf" %>
        <%= link_to "Account Settings", edit_user_path(@current_user), class: "dropdown-item font-nf" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Logout", logout_path ,method: "delete", class: "dropdown-item font-nf" %>
        </div>
      </li>

    </ul>
  </div>

</nav>

app/views/layouts/_navbar_login.html.erb
<nav class="navbar navbar-light">
<%= link_to image_tag("/images/notflix.png"), root_path, class: "navbar-brand ml-3 mt-2"%> </p>
</nav>

app/views/layouts/_navbar_main.html.erb
<nav class="navbar navbar-expand-md navbar-dark">
 <%=link_to image_tag("/images/notflix.png"), class: "navbar-brand ml-3 mt-2"%>

  <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item active">
        <%=link_to "Movies", movies_path, class: "nav-link text-white font-nf"%>
      </li>

      <li class="nav-item">
      <%=link_to "Genres", tags_path, class: "nav-link text-white font-nf"%>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white font-nf" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Welcome <%=@current_user.username.titleize %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to "Profile", profile_path(@current_profile), class: "dropdown-item font-nf" %>
        <%= link_to "Switch Profiles", user_path(@current_user), class: "dropdown-item font-nf" %>
        <%= link_to "Edit Profile Name", edit_profile_path(@current_profile), class: "dropdown-item font-nf" %>
        <%= link_to "Account Settings", edit_user_path(@current_user), class: "dropdown-item font-nf" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Logout", logout_path ,method: "delete", class: "dropdown-item font-nf" %>
        </div>
      </li>

    </ul>
  </div>

</nav>

app/views/layouts/_navbar_welcome.html.erb
<nav class="navbar navbar-light">
<%= link_to image_tag("/images/notflix.png"), root_path, class: "navbar-brand ml-3 mt-2"%> </p>
  <form class="form-inline">
  <%= link_to "Sign In", login_path, class:"text-white btn btn-danger mr-5 mt-1" %>
  </form>
</nav>

app/views/layouts/_testbg.html.erb
<<!DOCTYPE html>
<html>
<style>
* {
  box-sizing: border-box;
}
body {
  margin: 0;
  overflow: hidden;
 
}

.header {
  text-align: center;
  padding: 32px;
}

.row {
  float: center;
  width: 100%;
  padding: 0.5%;
  content: "";
  display: table;
  clear: both;
  overflow-wrap: normal;

}

.row img {
  margin-right: 0.5%;
  opacity: 0.5;
}





</style>
  <body >
    <% @pictures = Movie.all.map{|movie| "https://image.tmdb.org/t/p/w188_and_h282_bestv2" +movie.img} %>
    <% @posters = [] %>
    <% Movie.all.each do |movie| %>
      <% if movie.backdrop != nil %>
      <% @posters << "https://image.tmdb.org/t/p/w533_and_h300_bestv2/" + movie.backdrop %>
      <% end %>
    <% end %>
    <div style="transform: skew(-17deg); transform: rotateZ(15deg) perspective:200px; overflow: visible; scale(3.5,1.5); margin-right: -150px; margin-left: -150px; height: 200%;">
      <% 20.times do %>
        <div class="row" style="transform: skewY(10deg); width: 175%;">
          <% 6.times do %>
            <img src=<%= "#{@pictures.sample}" %> style="width:4%">
            <img src=<%= "#{@posters.sample}" %> style="width:10.6%">
          <% end %>
        </div>
        <div class="row" style="transform: skewY(10deg); width: 175%;">
          <% 3.times do %>
            <img src=<%= "#{@posters.sample}" %> style="width:10.6%">
            <img src=<%= "#{@posters.sample}" %> style="width:10.6%">
            <img src=<%= "#{@pictures.sample}" %> style="width:4%">
          <% end %>
        </div>
      <% end %>
    </div>
    </div>
  </body>
</html>

app/views/layouts/_welcome.html.erb
<header>
<div class="overlay"></div>

<div class="home-image">
  <%= render "/layouts/testbg" %>
</div>

<div>
  <%= render '/layouts/navbar_welcome' %>
</div>


<div class=" hero-card container h-100 ">
  <div class="d-flex h-100 text-center align-items-center ">
    <div class="w-100 text-white">
      <h1 class="display-3 col-12">Unlimited movies, TV shows, and more.</h1>
      <p class="byline lead mb-0">Watch anywhere. Cancel anytime.</p><br>
      <p><%= link_to "GET STARTED", signup_path, class: "sign-up btn btn-danger" %> </p>  <br>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notflix</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
  <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/movie_card.html.erb
<div class="container movie-card">
<div class="card card-1 my-2 shadow mx-1">

    <% if @parse.img == nil %>
        <% @info = TmdbApi.new(@parse.title).build_info %>
        <% @parse.update(description: @info[:description], img: @info[:image], backdrop: @info[:backdrop]) %>
    <% end %>

    <span class="mb-2 mt-1 movie-poster" ><%= link_to image_tag("https://image.tmdb.org/t/p/w188_and_h282_bestv2#{@parse.img}"), movie_path(@parse) %></span>
    <div class="hover-over mx-2"><%=@parse.likes.length%> Likes <br> <%= @parse.description %></div>
    <% if !@parse.list_movies.find_by("list_id = ?",@current_profile.list.id) %>
    <%= link_to "Add to Your List", "/addtolist/#{@parse.id}", :method => "post", :class => "btn btn-danger" %>
    <% else %>
    <%= link_to "Remove From Your list", "/removefromlist/#{@parse.id}", :method => "post", :class => "btn btn-dark" %>

    <% end %></p>
</div>

</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show"  role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      <button type ="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      </button>
    </ul>
  </div>
<% end %>_